### ISSUE TITLE
error occured when runing npm run serve

### ISSUE THREAD

**Issue by kowenzhang** [vincentzyc/vuecli3-admin#1]
ERROR  Failed to compile with 5 errors                                 09:12:32

These dependencies were not found:

* @/views/ad.vue in ./src/router.js
* @/views/home.vue in ./src/router.js
* @/views/login.vue in ./src/router.js

To install them, you can run: npm install --save @/views/ad.vue @/views/home.vue @/views/login.vue

These relative modules were not found:

* ./header.vue in ./node_modules/_cache-loader@1.2.5@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.4@babel-loader/lib!./node_modules/_cache-loader@1.2.5@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.4.2@vue-loader/lib??vue-loader-options!./src/components/layout/index.vue?vue&type=script&lang=js&
* ./sidebar.vue in ./node_modules/_cache-loader@1.2.5@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.4@babel-loader/lib!./node_modules/_cache-loader@1.2.5@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.4.2@vue-loader/lib??vue-loader-options!./src/components/layout/index.vue?vue&type=script&lang=js&

**Comment by vincentzyc** [comment]
Thank you for your feedback. The bug has been fixed.
